DirecaoCerta/Controllers/ContatoComercialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DirecaoCerta.Controllers
{
    public class ContatoComercialController : AplicationController
    {
        //
        // GET: /ContatoComercial/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Enviar(string nome, string email, string mensagem)
        {
            new MailController().EmailContatoComercial(nome, email, mensagem).DeliverAsync();

            ViewBag.Mensagem = "Seu e-mail foi enviado com sucesso. Em breve entraremos em contato.";

            //return RedirectToAction("Index", "Home");
            return View();
        }

    }
}

DirecaoCerta/Views/ContatoComercial/Enviar.cshtml
@{
    ViewBag.Title = "Enviar";
    Layout = "~/Views/Shared/_layout.home.cshtml";
}
@section secao_css
{
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")" />
}
@section js_render{
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap-modal.js")" type="text/javascript"></script>
}
<header>
    @Html.Partial("~/Views/Shared/_HeaderMenu.cshtml")

    <div class="slider-bg">
        <div class="container">
            @if (ViewBag.Mensagem != null)
            { 
                <div class="alert alert-success">
                    Obrigado!
                    <br />
                    @ViewBag.Mensagem
                </div>
            }
            <div class="span8">
            <h3>Contato Comercial</h3>
            
            <p>Permita-nos apresentar-lhe a solução ideal para controle de seus negócio, a través de uma ferramenta focada nas reais 
                necessidades de nossos clientes e em completa sintonia com as atuais tecnologias</p>

            @using (Html.BeginForm("Enviar", "ContatoComercial", FormMethod.Post, new { @class = "form-horizontal" }))
            { 
                <div class="control-group">
                    <input type="text" id="nome" name="nome" placeholder="Seu nome"></input>
                </div>
                   
                <div class="control-group">
                    <div class="input-append">
                        <input type="text" id="email" name="email" placeholder="Seu e-mail"></input>
                        <span class="add-on">@@</span>
                    </div>
                </div>

                <div class="control-group">
                    <textarea class="span8" id="mensagem" name="mensagem" placeholder="Mensagem" rows="10"></textarea>
                </div>

                <input class="btn btn-info" type="submit" value="Enviar" />
            }
        </div>
        </div>
    </div>
</header>

<address>
    <div class="container">
        <div class="span8">
            Bruno Borges de Góis <br />
            Telefone: (84) 8888-8888 <br /> 
            E-mail: bbgbruno@gmail.com
        </div>  
    </div>
</address>