DirecaoCerta/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirecaoCerta.Models;
using DirecaoCerta.Filters;
using WebMatrix.WebData;

namespace DirecaoCerta.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class AlunoController : AplicationController
    {
        private ContextoDeDados db = new ContextoDeDados();
        private int idEmpresa;

        //
        // GET: /Aluno/

        public ActionResult Index()
        {
            idEmpresa = IdEmpresaLogada();
            var pessoas = db.Alunos.Include(a => a.Empresa).Include(a => a.Endereco).Where(d => d.EmpresaId == idEmpresa);
            return View(pessoas.ToList());
        }

        //
        // GET: /Aluno/Details/5

        public ActionResult Details(int id = 0)
        {
            idEmpresa = IdEmpresaLogada();
            Aluno aluno = db.Alunos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            if (aluno == null)
            {
                return HttpNotFound();
            }
            return View(aluno);
        }

        //
        // GET: /Aluno/Create

        public ActionResult Create()
        {
            Aluno model = new Aluno();
            model.Endereco = new Endereco();
            return View(model);
        }

        //
        // POST: /Aluno/Create

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(Aluno aluno, Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                Auditoria auditoria = new Auditoria();
                auditoria.DataAtualizacao = DateTime.Today;
                auditoria.DataCadastro = DateTime.Today;
                auditoria.UserId = WebSecurity.CurrentUserId;
                auditoria.UltimaOperacao = "Inclusao";
                aluno.Auditoria = auditoria;
                aluno.EmpresaId = IdEmpresaLogada();
                aluno.Endereco = endereco;
                db.Alunos.Add(aluno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aluno);
        }

        //
        // GET: /Aluno/Edit/5

        public ActionResult Edit(int id = 0)
        {
            idEmpresa = IdEmpresaLogada();
            Aluno aluno = db.Alunos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            if (aluno == null)
            {
                return HttpNotFound();
            }

            return View(aluno);
        }

        //
        // POST: /Aluno/Edit/5

        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Edit(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aluno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aluno);
        }

        //
        // GET: /Aluno/Delete/5

        public ActionResult Delete(int id = 0)
        {
            idEmpresa = IdEmpresaLogada();
            Aluno aluno = db.Alunos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            if (aluno == null)
            {
                return HttpNotFound();
            }
            return View(aluno);
        }

        //
        // POST: /Aluno/Delete/5

        [HttpPost, ActionName("Delete")]
       // [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            idEmpresa = IdEmpresaLogada();
            Aluno aluno = db.Alunos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            if (aluno == null)
            {
                return HttpNotFound();
            }
            return View(aluno);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DirecaoCerta/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DirecaoCerta.Filters;
using DirecaoCerta.Models;
using WebMatrix.WebData;
using System.Text;

namespace DirecaoCerta.Controllers
{
    [InitializeSimpleMembership]
    public class EmpresaController : AplicationController
    {
        private ContextoDeDados db = new ContextoDeDados();
        public int idEmpresa;
       
        //
        // GET: /Empresa/

        public ActionResult Index()
        {

            idEmpresa = IdEmpresaLogada(); 
            return View(db.Empresas.Where(d => d.Id == idEmpresa).ToList());
        }

        //
        // GET: /Empresa/Details/5

        public ActionResult Details()
        {
            idEmpresa = IdEmpresaLogada(); 
            Empresa empresa = db.Empresas.Find(idEmpresa);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        //
        // GET: /Empresa/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Empresa/Create

        public string CreatePassword(int tamanho)
        {
            const string SenhaCaracteresValidos = "abcdefghijklmnopqrstuvwxyz1234567890@#!?";
            int valormaximo = SenhaCaracteresValidos.Length;
            Random random = new Random(DateTime.Now.Millisecond);
            StringBuilder senha = new StringBuilder(tamanho);
            for (int indice = 0; indice < tamanho; indice++)
                senha.Append(SenhaCaracteresValidos[random.Next(0, valormaximo)]);
            return senha.ToString();
        }

        public static string soNumero(string toNormalize)
        {
            List<char> numbers = new List<char>("0123456789");
            StringBuilder toReturn = new StringBuilder(toNormalize.Length);
            CharEnumerator enumerator = toNormalize.GetEnumerator();

            while (enumerator.MoveNext())
            {
                if (numbers.Contains(enumerator.Current))
                    toReturn.Append(enumerator.Current);
            }

            return toReturn.ToString();
        }

        [HttpPost]
        public ActionResult Create(Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                RegisterModel novoUsuario = new RegisterModel();
                empresa.CNPJ = soNumero(empresa.CNPJ);
                novoUsuario.UserName = empresa.Usuario;
                novoUsuario.Password = "master";
                //CreatePassword(8);
                db.Empresas.Add(empresa);
                
                WebSecurity.CreateUserAndAccount(novoUsuario.UserName, novoUsuario.Password); //gerar senha automatica 
                empresa.UserId = WebSecurity.GetUserId(novoUsuario.UserName);   //Mandar email com a senha para o usuario

                String mensagem = "Usuário : " + novoUsuario.UserName + " / Senha : " + novoUsuario.Password;
                new MailController().CadastroNovaEmpresa(empresa, novoUsuario.Password, mensagem).Deliver();
                ViewBag.Mensagem = "Um e-mail com usuário e senha foi enviado para " + empresa.Email;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
 
            return View(empresa);
        }

        //
        // GET: /Empresa/Edit/5

        public ActionResult Edit()
        {
            idEmpresa = IdEmpresaLogada(); 
            Empresa empresa = db.Empresas.Find(idEmpresa);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        //
        // POST: /Empresa/Edit/5

        [HttpPost]
        public ActionResult Edit(Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(empresa);
        }

        //
        // GET: /Empresa/Delete/5

        public ActionResult Delete()
        {
            idEmpresa = IdEmpresaLogada(); 
            Empresa empresa = db.Empresas.Find(idEmpresa);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        //
        // POST: /Empresa/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            idEmpresa = IdEmpresaLogada(); 
            Empresa empresa = db.Empresas.Find(idEmpresa);
            db.Empresas.Remove(empresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DirecaoCerta/Controllers/ServicoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirecaoCerta.Filters;
using DirecaoCerta.Models;
using WebMatrix.WebData;

namespace DirecaoCerta.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class ServicoController : AplicationController
    {
        private ContextoDeDados db = new ContextoDeDados();
        public int idEmpresa;

        //
        // GET: /Servico/

        public ActionResult Index()
        {
            int idEmpresa = IdEmpresaLogada();
            var servicos = db.Servicos.Include(s => s.Empresa).Include(s => s.Auditoria).Where(d => d.EmpresaId == idEmpresa);
            return View(servicos.ToList());
        }
        
        //
        // GET: /Servico/Details/5

        public ActionResult Details(int id = 0)
        {
            Servico servico = db.Servicos.Find(id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        //
        // GET: /Servico/Create

        public ActionResult Create()
        {

            ViewBag.EmpresaId = IdEmpresaLogada();
            ViewBag.AuditoriaId = new SelectList(db.Auditoria, "Id", "UltimaOperacao");
            return View();
        }

        //
        // POST: /Servico/Create

        [HttpPost]
        public ActionResult Create(Servico servico)
        {
            

            if (ModelState.IsValid)
            {
                Auditoria auditoria = new Auditoria();
                auditoria.DataAtualizacao = DateTime.Today;
                auditoria.DataCadastro = DateTime.Today;
                auditoria.UserId = WebSecurity.CurrentUserId;
                auditoria.UltimaOperacao = "Inclusao";
                servico.Auditoria = auditoria;
                servico.EmpresaId = IdEmpresaLogada();
                db.Servicos.Add(servico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpresaId = new SelectList(db.Empresas, "Id", "RazaoSocial", servico.EmpresaId);
            ViewBag.AuditoriaId = new SelectList(db.Auditoria, "Id", "UltimaOperacao", servico.AuditoriaId);
            return View(servico);
        }

        //
        // GET: /Servico/Edit/5

        public ActionResult Edit(int id = 0)
        {
            idEmpresa = IdEmpresaLogada();
            Servico servico = db.Servicos.Where( d => d.Id==id && d.EmpresaId == idEmpresa).First();
            if (servico == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpresaId = new SelectList(db.Empresas, "Id", "RazaoSocial", servico.EmpresaId);
            ViewBag.AuditoriaId = new SelectList(db.Auditoria, "Id", "UltimaOperacao", servico.AuditoriaId);
            return View(servico);
        }

        //
        // POST: /Servico/Edit/5

        [HttpPost]
        public ActionResult Edit(Servico servico)
        {
            if (ModelState.IsValid)
            {
                idEmpresa = IdEmpresaLogada();
                servico.EmpresaId = idEmpresa;
                servico.Empresa = db.Empresas.Where(e => e.Id == idEmpresa).FirstOrDefault();
                servico.Auditoria = db.Auditoria.Find(servico.AuditoriaId);
                servico.Auditoria.UltimaOperacao = "Alteração";
                db.Entry(servico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuditoriaId = new SelectList(db.Auditoria, "Id", "UltimaOperacao", servico.AuditoriaId);
            return View(servico);
        }

        //
        // GET: /Servico/Delete/5

        public ActionResult Delete(int id = 0)
        {
            int idEmpresa = IdEmpresaLogada();
            Servico servico = db.Servicos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        //
        // POST: /Servico/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            int idEmpresa = IdEmpresaLogada();
            Servico servico = db.Servicos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            db.Servicos.Remove(servico);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DirecaoCerta/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirecaoCerta.Models;
using WebMatrix.WebData;

namespace DirecaoCerta.Controllers
{
    public class VeiculoController : AplicationController
    {
        private ContextoDeDados db = new ContextoDeDados();
        
        
        //
        // GET: /Veiculos/

        public ActionResult Index()
        {
            int idEmpresa = IdEmpresaLogada();
            var veiculos = db.Veiculos.Include(v => v.Empresa).Include(v => v.Auditoria).Where(d => d.EmpresaId == idEmpresa); 
            return View(veiculos.ToList()); 
        }

        //
        // GET: /Veiculos/Details/5

        public ActionResult Details(int id = 0)
        {
            Veiculo veiculo = db.Veiculos.Find(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        //
        // GET: /Veiculos/Create

        public ActionResult Create()
        {
            ViewBag.EmpresaId = IdEmpresaLogada();
            return View();
        }

        //
        // POST: /Veiculos/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                Auditoria auditoria = new Auditoria();
                auditoria.DataAtualizacao = DateTime.Today;
                auditoria.DataCadastro = DateTime.Today;
                auditoria.UserId = WebSecurity.CurrentUserId;
                auditoria.UltimaOperacao = "Inclusao";
                veiculo.Auditoria = auditoria;
                veiculo.EmpresaId = IdEmpresaLogada();
                db.Veiculos.Add(veiculo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(veiculo);
        }

        //
        // GET: /Veiculos/Edit/5

        public ActionResult Edit(int id = 0)
        {
            int idEmpresa = IdEmpresaLogada();
            Veiculo veiculo = db.Veiculos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        //
        // POST: /Veiculos/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                int idEmpresa = IdEmpresaLogada();
                veiculo.EmpresaId = idEmpresa;
                veiculo.Auditoria = db.Auditoria.Find(veiculo.AuditoriaId);
                veiculo.Auditoria.UltimaOperacao = "Alteração";
                db.Entry(veiculo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(veiculo);
        }

        //
        // GET: /Veiculos/Delete/5

        public ActionResult Delete(int id = 0)
        {
            int idEmpresa = IdEmpresaLogada();
            Veiculo veiculo = db.Veiculos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        //
        // POST: /Veiculos/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int idEmpresa = IdEmpresaLogada();
            Veiculo veiculo = db.Veiculos.Where(d => d.Id == id && d.EmpresaId == idEmpresa).First();
            db.Veiculos.Remove(veiculo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

DirecaoCerta/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <ul>
        <li>@Html.ActionLink("Página incial", "Index", "Home")</li>
        <li>@Html.ActionLink("Sobre", "About", "Home")</li>
        <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
    </ul>
</aside>

DirecaoCerta/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

DirecaoCerta/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Direção Certa - Sistema para controle de CFCs";
}

@section css{
	<link href="@Url.Content("~/Content/screen.css")" rel="stylesheet" type="text/css" />
}
@section analytics{
	<script type="text/javascript">

		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-26110636-1']);
		_gaq.push(['_trackPageview']);

		(function () {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	
	</script>
}
@section scripts{
	<script src="@Url.Content("~/Scripts/easySlider1.7.js")" type="text/javascript"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$("#slider").easySlider({
				auto: true,
				continuous: true,
				controlsShow: false,
				pause: 4000
			});

		});	
	</script>
}
@Html.Partial("~/Views/Shared/_Menu.cshtml")
<div class="page-header header-orange ">
	<div class="page-header-content image-top-home">
		<div class="content">
			<h1>
				Pensando
				<br />
				simples.</h1>
			<h2>
				Ataque a complexidade dos processos de gestão
				<br />
				de sua auto escola garantindo bons resultados
				<br />
				com o <b class="mark">Direção Certa</b>
			</h2>
		</div>
	</div>
</div>
<div class="content">
	<div class="box info" style="width: 400px; height: 250px">
		<h2>
			Você precisa de um sistema para CFC</h2>
		O sistema Direção Certa tem como objetivo permitir um controle fácil de todos
		os processos de uma Auto Escola (CFC). Participe de nossa enquete e nos ajude a
		aperfeiçoar esta ferramenta.
		<br />
		<br />
		<a class="button orange" href="https://docs.google.com/spreadsheet/viewform?formkey=dGRTbUFpa0Vmd0VmV2pyYW45MUJ5VkE6MQ">
			Participe de nossa enquete</a>
	</div>
	<div class="box info" style="width: 500px; height: 250px">
		<div id="slider-content">
			<div id="slider">
				<ul style="height: 250px">
					<li><a href="#">
						<div class="text-slider" style="float: left">
							<h2>
								Evite custos excessivos em ligações</h2>
							Crie um elo inteligente entre você e seu aluno e evite custos desnecessários.
							<br />
							<br />
						</div>
						<img src="../../Content/images/control-img1.jpg" alt="Css Template Preview" />
					</a></li>
					<li><a href="#">
						<div class="text-slider" style="float: left; margin-right: 5px">
							<h2>
								Agendamento simples e seguro</h2>
							Planeje os agendamentos das aulas práticas dos alunos de forma rápida e sem transtorno...
							<br />
							<br />
						</div>
						<img src="../../Content/images/bg_top_home.jpg" alt="Css Template Preview" />
					</a></li>
					<li><a href=@Url.Action("Index", "Home", new { area = "" })>
						<div class="text-slider" style="float: left; margin-right: 5px">
							<h2>
								Ofereça o melhor para seus alunos</h2>
							Um acesso simples e fácil para o acompanhamento das ocorrências geradas a partir
							do seu Centro de Formação de Condutores.
							<br />
						</div>
						<img src="../../Content/images/aluno.jpg" alt="Css Template Preview" />
					</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

DirecaoCerta/Views/Home/Menu.cshtml
@{
    ViewBag.Title = "Página inicial";
    
}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Direção certa</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <h5>@ViewBag.Message</h5>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Direção Certa", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Início", "Index", "Home")</li>
                            <li>@Html.ActionLink("Empresas", "Index", "Empresa")</li>
                            <li>@Html.ActionLink("Alunos", "Index", "Aluno")</li>
                            <li>@Html.ActionLink("Serviços", "Index", "Servico")</li>
                            <li>@Html.ActionLink("Matriculas", "Index", "Matricula")</li>
                            <li>@Html.ActionLink("Veículos", "Index", "Veiculo")</li>
                            <li>@Html.ActionLink("Tipos de Pagamentos", "Index", "TipoPagamento")</li>
                            <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Direção Certa</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
      </body>
</html>